### PR TITLE
Moving security-hq to Ubuntu 16.04 Xenial

### PR DESCRIPTION
**Pull request by shtukas**
This change moves security-hq from Ubuntu Trusty to Ubuntu 16.04 Xenial. Most of the work consisted in moving to systemd. 

Thanks @aug24 for helping!

### CODE REVIEW

**Comment by shtukas** [comment]
+1 for @JustinPinner 's changes

**Comment by shtukas** [comment]
Branch will be squashed before merging to master.

**Comment by aug24** [comment]
+1 here.  But I'm not Justin Pinner!

**Comment by shtukas** [comment]
Corrected, I sometimes forgot to be careful about the `[at]justin` completion :)

**Pull request merged**
